require 'inforouter/errors/inforouter_error'
require 'inforouter/errors/missing_config_error'
require 'inforouter/errors/missing_config_option_error'
require 'inforouter/errors/soap_error'
require 'inforouter/errors/unexpected_soap_response_error.rb'
require 'inforouter/errors/api_error'
